name: Scala CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: olafurpg/setup-scala@v2
      - name: Install PostgreSQL 9.6 client
        run: |
          sudo apt update
          sudo bash -c "echo deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main >> /etc/apt/sources.list.d/pgdg.list"
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev postgresql-client-9.6
      - name: Setup db
        run: |
          psql -c 'create database travis_ci_test;' -U postgres -h 127.0.0.1
          psql -c 'create user lch;' -U postgres -h 127.0.0.1
          psql -c 'create database lch_test;' -U postgres -h 127.0.0.1
          psql -c 'grant all privileges on database lch_test to lch;' -U postgres -h 127.0.0.1
          psql -c 'create database lch_dev;' -U postgres -h 127.0.0.1
          psql -c 'grant all privileges on database lch_dev to lch;' -U postgres -h 127.0.0.1
      - name: Setup credentials
        run: |
          svn --username ${{ secrets.SVN_USERNAME }} --password ${{ secrets.SVN_PASSWORD }} --non-interactive co http://source.gemini.edu/software/lch-credentials ./lch-credentials
          bash ./lch-credentials/trunk/link.sh -v .
      - name: Run tests
        run: mvn -B clean install
